Exercise
-------





https://www.kaggle.com/yersever/500-person-gender-height-weight-bodymassindex

**********************************************

In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv('C:\\Users\\Acer\\OneDrive\\Documents\\epslion\\500_Person_Gender_Height_Weight_Index.csv')
df.head()

Gender  Height  Weight  Index
0    Male     174      96      4
1    Male     189      87      2
2  Female     185     110      4
3  Female     195     104      3
4    Male     149      61      3

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   Gender  500 non-null    object
 1   Height  500 non-null    int64 
 2   Weight  500 non-null    int64 
 3   Index   500 non-null    int64 
dtypes: int64(3), object(1)
memory usage: 15.8+ KB


In [4]:
data=df.iloc[:,-3:].values
data

array([[174,  96,   4],
       [189,  87,   2],
       [185, 110,   4],
       ...,
       [141, 136,   5],
       [150,  95,   5],
       [173, 131,   5]], dtype=int64)

In [5]:
# 1- Find the number of dimensions, the size and the shape of this array
print(data.ndim)
print(data.size)
print(data.shape)

2
1500
(500, 3)


In [6]:
# 2- What is the data type of this array? 
print(data.dtype)

int64


In [8]:
# 3- Return the target value of the 500 observations
target=data[:,2]
target

array([4, 2, 4, 3, 3, 3, 5, 5, 3, 4, 2, 4, 3, 2, 2, 5, 5, 5, 5, 5, 5, 5,
       4, 5, 2, 3, 3, 1, 5, 5, 5, 1, 1, 5, 5, 4, 3, 4, 5, 2, 4, 5, 2, 5,
       4, 2, 4, 4, 3, 5, 5, 1, 5, 4, 4, 3, 4, 5, 3, 5, 0, 5, 0, 2, 5, 5,
       4, 2, 4, 4, 2, 4, 5, 2, 3, 4, 4, 4, 4, 0, 3, 5, 3, 4, 5, 0, 5, 5,
       5, 5, 5, 3, 3, 2, 4, 5, 4, 5, 1, 0, 4, 5, 5, 4, 4, 4, 5, 5, 4, 3,
       4, 5, 4, 2, 4, 3, 2, 5, 5, 5, 4, 4, 4, 5, 5, 4, 4, 4, 5, 2, 5, 2,
       5, 4, 5, 5, 5, 3, 5, 5, 2, 4, 5, 5, 5, 4, 3, 5, 3, 3, 0, 3, 3, 5,
       5, 4, 3, 5, 3, 4, 2, 2, 3, 5, 4, 2, 4, 5, 3, 2, 4, 5, 5, 4, 4, 4,
       4, 3, 5, 3, 3, 4, 4, 2, 3, 3, 5, 3, 5, 4, 5, 5, 4, 5, 5, 5, 4, 4,
       5, 5, 1, 3, 4, 4, 5, 4, 5, 4, 3, 4, 4, 5, 5, 5, 0, 5, 5, 5, 5, 5,
       2, 5, 4, 5, 0, 5, 3, 4, 5, 5, 4, 2, 3, 3, 4, 3, 5, 5, 2, 5, 3, 2,
       1, 5, 0, 5, 3, 5, 3, 4, 3, 5, 5, 5, 5, 2, 4, 5, 5, 4, 5, 5, 5, 2,
       4, 5, 5, 5, 5, 1, 5, 5, 4, 0, 3, 3, 4, 2, 3, 1, 1, 5, 5, 4, 4, 4,
       4, 5, 2, 5, 4, 3, 3, 4, 5, 5, 2, 4, 3, 4, 5,

In [13]:
# 4- Extract every 3 observations of the data
data[::3,:]

array([[174,  96,   4],
       [195, 104,   3],
       [147,  92,   5],
       [169, 103,   4],
       [192, 101,   3],
       [153, 107,   5],
       [144, 145,   5],
       [153, 149,   5],
       [172,  67,   2],
       [187,  62,   1],
       [153, 121,   5],
       [160, 131,   5],
       [197, 114,   3],
       [185,  81,   2],
       [157,  56,   2],
       [185,  76,   2],
       [161,  72,   3],
       [176,  54,   1],
       [196, 116,   4],
       [178, 127,   5],
       [191,  54,   0],
       [190,  83,   2],
       [172,  96,   4],
       [194, 136,   4],
       [141,  80,   5],
       [197, 154,   4],
       [176, 122,   4],
       [166, 140,   5],
       [168, 123,   5],
       [145, 117,   5],
       [178, 154,   5],
       [177,  61,   2],
       [142,  69,   4],
       [190,  50,   0],
       [161, 155,   5],
       [195, 126,   4],
       [181, 106,   4],
       [146, 157,   5],
       [177,  96,   4],
       [146, 104,   5],
       [168,  87,   4],
       [184, 160

In [23]:
# 5- Extract the first and last columns in one array. (using hstack)
c1=data[::,0]#FOR THE FIRST COLUMN
C3=data[::,-1]#for the last coloumn
np.hstack((c1.reshape(500,1),C3.reshape(500,1)))

array([[174,   4],
       [189,   2],
       [185,   4],
       [195,   3],
       [149,   3],
       [189,   3],
       [147,   5],
       [154,   5],
       [174,   3],
       [169,   4],
       [195,   2],
       [159,   4],
       [192,   3],
       [155,   2],
       [191,   2],
       [153,   5],
       [157,   5],
       [140,   5],
       [144,   5],
       [172,   5],
       [157,   5],
       [153,   5],
       [169,   4],
       [185,   5],
       [172,   2],
       [151,   3],
       [190,   3],
       [187,   1],
       [163,   5],
       [179,   5],
       [153,   5],
       [178,   1],
       [195,   1],
       [160,   5],
       [157,   5],
       [189,   4],
       [197,   3],
       [144,   4],
       [171,   5],
       [185,   2],
       [175,   4],
       [149,   5],
       [157,   2],
       [161,   5],
       [182,   4],
       [185,   2],
       [188,   4],
       [181,   4],
       [161,   3],
       [140,   5],
       [168,   5],
       [176,   1],
       [163,

In [28]:
# 6- Reverse the array (the last obseravtion becomes the first)

#data[::-1]
data[:,::-1]

array([[  4,  96, 174],
       [  2,  87, 189],
       [  4, 110, 185],
       ...,
       [  5, 136, 141],
       [  5,  95, 150],
       [  5, 131, 173]], dtype=int64)

In [35]:
# 7- What is the maximum and minimum height?
height= data[:,0]
Maxheight=height.max()
Minheight=height.min()
print('The maximum height= ',Maxheight, 'cm',',The minimum height = ',Minheight,'cm')

The maximum height=  199 cm ,The minimum height =  140 cm


In [38]:
# 8- What is the maximum and minimum weight?
weight=data[:,1]
Maxweight=weight.max()
Minweight=weight.min()
print('The max weight = ',Maxweight,'Kg',', The mininmum weight= ',Minweight,'kg' )

The max weight =  160 Kg , The mininmum weight=  50 kg


In [43]:
# 9- Find the mean and standard deviation of height using the simple operations only. (np.sum) 
mean=height.sum()/height.size
print('Mean :',mean)

Mean : 169.944


In [49]:
diff=height-mean
squered=np.power(diff,2)
Sum=np.sum(squered)
n=height.size
div=Sum/(n-1)
standard_deviation=np.sqrt(div)
print('standard deviation :',standard_deviation )

standard deviation : 16.375260679593755


In [50]:
# 10- Find the mean and standard deviation of weight using the simple operations only.
mean=weight.sum()/weight.shape[0]
mean

106.0

In [62]:
dif=weight-mean
powr=np.power(dif,2)
summ=np.sum(powr)
n=weight.size
div=summ/(n-1)
standard_deviation=np.sqrt(div)
print('standard deviation :', standard_deviation)


standard deviation : 32.38260746964435


In [64]:
# 11- Find the mean and standard deviation of height.
MeanOFHieght=np.mean(height)
StanderdDev=np.std(height)
print('The mean :',MeanOFHieght,'The standerd divaition',StanderdDev)


The mean : 169.944 The standerd divaition 16.35887722308594


In [65]:
# 12- Find the mean and standard deviation of weight..
MeanOFweight=np.mean(weight )
stdofweight=np.std(weight)
print('The mean :' ,MeanOFweight,'The std :',stdofweight)

The mean : 106.0 The std : 32.350208654659404


In [67]:
# 13- Find the 25th, 75th percentile and the median for height
np.percentile(height,[25,50,75])

array([156. , 170.5, 184. ])

In [69]:
# 14- Find the 25th, 75th percentile and the median for weight
np.percentile(weight,[25,50,75])

array([ 80., 106., 136.])

In [71]:
# 15- Normalize height and weight
Norofheight=(height-MeanOFHieght)/StanderdDev
NorOFweight=(weight-MeanOFweight)/stdofweight
print('Normalize height and weight : ',Norofheight,NorOFweight)

Normalize height and weight :  [ 0.24793878  1.16487212  0.92035656  1.53164546 -1.28028346  1.16487212
 -1.40254124 -0.97463902  0.24793878 -0.05770567  1.53164546 -0.66899457
  1.34825879 -0.91351013  1.2871299  -1.03576791 -0.79125235 -1.83044347
 -1.58592791  0.125681   -0.79125235 -1.03576791 -0.05770567  0.92035656
  0.125681   -1.15802568  1.22600101  1.04261434 -0.42447901  0.55358322
 -1.03576791  0.49245433  1.53164546 -0.60786568 -0.79125235  1.16487212
  1.65390324 -1.58592791  0.06455211  0.92035656  0.30906767 -1.28028346
 -0.79125235 -0.54673679  0.73696989  0.92035656  1.10374323  0.675841
 -0.54673679 -1.83044347 -0.11883456  0.37019656 -0.42447901  0.125681
  1.59277435  1.04261434  0.125681    0.49245433 -0.36335012 -1.6470568
  1.2871299  -1.76931458  1.40938768  1.22600101  0.30906767  0.55358322
  0.125681   -0.11883456 -0.36335012  1.47051657 -1.03576791  0.49245433
 -1.76931458  0.61471211  0.92035656  1.65390324 -0.30222123 -0.11883456
  0.37019656  0.675841   

In [74]:
# Min max scaler
scaler=(height-np.min(height))/(np.max(height)-np.min(height))
print(' Min max scaler :',scaler)

 Min max scaler : [0.57627119 0.83050847 0.76271186 0.93220339 0.15254237 0.83050847
 0.11864407 0.23728814 0.57627119 0.49152542 0.93220339 0.3220339
 0.88135593 0.25423729 0.86440678 0.22033898 0.28813559 0.
 0.06779661 0.54237288 0.28813559 0.22033898 0.49152542 0.76271186
 0.54237288 0.18644068 0.84745763 0.79661017 0.38983051 0.66101695
 0.22033898 0.6440678  0.93220339 0.33898305 0.28813559 0.83050847
 0.96610169 0.06779661 0.52542373 0.76271186 0.59322034 0.15254237
 0.28813559 0.3559322  0.71186441 0.76271186 0.81355932 0.69491525
 0.3559322  0.         0.47457627 0.61016949 0.38983051 0.54237288
 0.94915254 0.79661017 0.54237288 0.6440678  0.40677966 0.05084746
 0.86440678 0.01694915 0.89830508 0.84745763 0.59322034 0.66101695
 0.54237288 0.47457627 0.40677966 0.91525424 0.22033898 0.6440678
 0.01694915 0.6779661  0.76271186 0.96610169 0.42372881 0.47457627
 0.61016949 0.69491525 0.40677966 0.44067797 0.84745763 0.77966102
 0.47457627 0.98305085 0.59322034 0.08474576 0.3220339

In [75]:
# 16- What are the indices of the tallest people? 
np.argmax(height)

100

In [77]:
# Sometimes, in logistic regression, for example, we need to find a polynomial fitting function.
# For that, we need to create a new column for each feature representing a higher degree for that feature.

# 17- Create two arrays representing the square of both height and weight
heightpower=height**2
heightpower

array([30276, 35721, 34225, 38025, 22201, 35721, 21609, 23716, 30276,
       28561, 38025, 25281, 36864, 24025, 36481, 23409, 24649, 19600,
       20736, 29584, 24649, 23409, 28561, 34225, 29584, 22801, 36100,
       34969, 26569, 32041, 23409, 31684, 38025, 25600, 24649, 35721,
       38809, 20736, 29241, 34225, 30625, 22201, 24649, 25921, 33124,
       34225, 35344, 32761, 25921, 19600, 28224, 30976, 26569, 29584,
       38416, 34969, 29584, 31684, 26896, 20449, 36481, 19881, 37249,
       36100, 30625, 32041, 29584, 28224, 26896, 37636, 23409, 31684,
       19881, 32400, 34225, 38809, 27225, 28224, 30976, 32761, 26896,
       27556, 36100, 34596, 28224, 39204, 30625, 21025, 25281, 34225,
       31684, 33489, 37636, 31329, 38809, 28900, 20164, 25600, 38025,
       36100, 39601, 23716, 25921, 39204, 36864, 38025, 27556, 25281,
       32761, 22201, 22500, 21316, 36100, 36864, 31329, 21904, 27225,
       21316, 20736, 30976, 28224, 34969, 34969, 33856, 24964, 24964,
       37636, 21025,

In [78]:
# 18- Create two arrays representing the square root of both height and weight
heightsqrt=np.sqrt(height)
heightsqrt

array([13.19090596, 13.74772708, 13.60147051, 13.96424004, 12.20655562,
       13.74772708, 12.12435565, 12.40967365, 13.19090596, 13.        ,
       13.96424004, 12.60952021, 13.85640646, 12.4498996 , 13.82027496,
       12.36931688, 12.52996409, 11.83215957, 12.        , 13.11487705,
       12.52996409, 12.36931688, 13.        , 13.60147051, 13.11487705,
       12.28820573, 13.78404875, 13.67479433, 12.76714533, 13.37908816,
       12.36931688, 13.34166406, 13.96424004, 12.64911064, 12.52996409,
       13.74772708, 14.03566885, 12.        , 13.07669683, 13.60147051,
       13.22875656, 12.20655562, 12.52996409, 12.68857754, 13.49073756,
       13.60147051, 13.7113092 , 13.45362405, 12.68857754, 11.83215957,
       12.9614814 , 13.26649916, 12.76714533, 13.11487705, 14.        ,
       13.67479433, 13.11487705, 13.34166406, 12.80624847, 11.95826074,
       13.82027496, 11.87434209, 13.89244399, 13.78404875, 13.22875656,
       13.37908816, 13.11487705, 12.9614814 , 12.80624847, 13.92

In [79]:
# 19- Extract the last column of the data (the target). What will be its shape?
target

array([4, 2, 4, 3, 3, 3, 5, 5, 3, 4, 2, 4, 3, 2, 2, 5, 5, 5, 5, 5, 5, 5,
       4, 5, 2, 3, 3, 1, 5, 5, 5, 1, 1, 5, 5, 4, 3, 4, 5, 2, 4, 5, 2, 5,
       4, 2, 4, 4, 3, 5, 5, 1, 5, 4, 4, 3, 4, 5, 3, 5, 0, 5, 0, 2, 5, 5,
       4, 2, 4, 4, 2, 4, 5, 2, 3, 4, 4, 4, 4, 0, 3, 5, 3, 4, 5, 0, 5, 5,
       5, 5, 5, 3, 3, 2, 4, 5, 4, 5, 1, 0, 4, 5, 5, 4, 4, 4, 5, 5, 4, 3,
       4, 5, 4, 2, 4, 3, 2, 5, 5, 5, 4, 4, 4, 5, 5, 4, 4, 4, 5, 2, 5, 2,
       5, 4, 5, 5, 5, 3, 5, 5, 2, 4, 5, 5, 5, 4, 3, 5, 3, 3, 0, 3, 3, 5,
       5, 4, 3, 5, 3, 4, 2, 2, 3, 5, 4, 2, 4, 5, 3, 2, 4, 5, 5, 4, 4, 4,
       4, 3, 5, 3, 3, 4, 4, 2, 3, 3, 5, 3, 5, 4, 5, 5, 4, 5, 5, 5, 4, 4,
       5, 5, 1, 3, 4, 4, 5, 4, 5, 4, 3, 4, 4, 5, 5, 5, 0, 5, 5, 5, 5, 5,
       2, 5, 4, 5, 0, 5, 3, 4, 5, 5, 4, 2, 3, 3, 4, 3, 5, 5, 2, 5, 3, 2,
       1, 5, 0, 5, 3, 5, 3, 4, 3, 5, 5, 5, 5, 2, 4, 5, 5, 4, 5, 5, 5, 2,
       4, 5, 5, 5, 5, 1, 5, 5, 4, 0, 3, 3, 4, 2, 3, 1, 1, 5, 5, 4, 4, 4,
       4, 5, 2, 5, 4, 3, 3, 4, 5, 5, 2, 4, 3, 4, 5,

In [81]:
# 20- make it a column vector
target.reshape((500,1))

array([[4],
       [2],
       [4],
       [3],
       [3],
       [3],
       [5],
       [5],
       [3],
       [4],
       [2],
       [4],
       [3],
       [2],
       [2],
       [5],
       [5],
       [5],
       [5],
       [5],
       [5],
       [5],
       [4],
       [5],
       [2],
       [3],
       [3],
       [1],
       [5],
       [5],
       [5],
       [1],
       [1],
       [5],
       [5],
       [4],
       [3],
       [4],
       [5],
       [2],
       [4],
       [5],
       [2],
       [5],
       [4],
       [2],
       [4],
       [4],
       [3],
       [5],
       [5],
       [1],
       [5],
       [4],
       [4],
       [3],
       [4],
       [5],
       [3],
       [5],
       [0],
       [5],
       [0],
       [2],
       [5],
       [5],
       [4],
       [2],
       [4],
       [4],
       [2],
       [4],
       [5],
       [2],
       [3],
       [4],
       [4],
       [4],
       [4],
       [0],
       [3],
       [5],
       [3],
    

In [83]:
# 20- make it a row vector
#target.reshape((1,500))
target.reshape((1,-1))

array([[4, 2, 4, 3, 3, 3, 5, 5, 3, 4, 2, 4, 3, 2, 2, 5, 5, 5, 5, 5, 5, 5,
        4, 5, 2, 3, 3, 1, 5, 5, 5, 1, 1, 5, 5, 4, 3, 4, 5, 2, 4, 5, 2, 5,
        4, 2, 4, 4, 3, 5, 5, 1, 5, 4, 4, 3, 4, 5, 3, 5, 0, 5, 0, 2, 5, 5,
        4, 2, 4, 4, 2, 4, 5, 2, 3, 4, 4, 4, 4, 0, 3, 5, 3, 4, 5, 0, 5, 5,
        5, 5, 5, 3, 3, 2, 4, 5, 4, 5, 1, 0, 4, 5, 5, 4, 4, 4, 5, 5, 4, 3,
        4, 5, 4, 2, 4, 3, 2, 5, 5, 5, 4, 4, 4, 5, 5, 4, 4, 4, 5, 2, 5, 2,
        5, 4, 5, 5, 5, 3, 5, 5, 2, 4, 5, 5, 5, 4, 3, 5, 3, 3, 0, 3, 3, 5,
        5, 4, 3, 5, 3, 4, 2, 2, 3, 5, 4, 2, 4, 5, 3, 2, 4, 5, 5, 4, 4, 4,
        4, 3, 5, 3, 3, 4, 4, 2, 3, 3, 5, 3, 5, 4, 5, 5, 4, 5, 5, 5, 4, 4,
        5, 5, 1, 3, 4, 4, 5, 4, 5, 4, 3, 4, 4, 5, 5, 5, 0, 5, 5, 5, 5, 5,
        2, 5, 4, 5, 0, 5, 3, 4, 5, 5, 4, 2, 3, 3, 4, 3, 5, 5, 2, 5, 3, 2,
        1, 5, 0, 5, 3, 5, 3, 4, 3, 5, 5, 5, 5, 2, 4, 5, 5, 4, 5, 5, 5, 2,
        4, 5, 5, 5, 5, 1, 5, 5, 4, 0, 3, 3, 4, 2, 3, 1, 1, 5, 5, 4, 4, 4,
        4, 5, 2, 5, 4, 3, 3, 4, 5, 5, 